Update resources.json
timdeschryver/hacktoberfest-2019-angular pull request #171
Opened 2020-10-09 13:48 UTC by shuaibabs

Heyy their
i have updated resourses.json and i also resolved the conflict

2020-10-11 14:28 UTC, timdeschryver requested changes
It seems like the JSON is duplicated, could you just add your resource to the list?

2020-10-11 16:12 UTC, shuaibabs commented
> It seems like the JSON is duplicated, could you just add your resource to the list?

Okk I'll do that

2020-10-12 07:43 UTC, shuaibabs commented
> It seems like the JSON is duplicated, could you just add your resource to the list?

Could you please label this PR with the label "hacktoberfest-accepted" before you merge it? :)

2020-10-12 10:47 UTC, timdeschryver approved these changes

2020-10-12 10:47 UTC, merged